removed all toString() calls on sys.exc_info() error handlers as this isn't always available and may obscure real error by causing: 'exceptions.AttributeError' object has no attribute 'toString'